version: "3.7"
services:
  nethermind-xdai:
    image: nethermind/nethermind:latest
    container_name: nethermind
    restart: always
    env_file: .env
    stop_grace_period: 2m
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${WS_PORT}:${WS_PORT}
      - ${P2P_PORT}:${P2P_PORT}/tcp
      - ${P2P_PORT}:${P2P_PORT}/udp
    command:
      - --datadir
      - /var/lib/nethermind
      - --Init.WebSocketsEnabled
      - "true"
      - --Network.DiscoveryPort
      - "${P2P_PORT}"
      - --Network.P2PPort
      - "${P2P_PORT}"
      - --HealthChecks.Enabled
      - "true"
      - --HealthChecks.UIEnabled
      - "true"
      - --JsonRpc.Enabled
      - "true"
      - --JsonRpc.EnabledModules
      - "Web3,Eth,Subscribe,Net,Parity"
      - --JsonRpc.Host
      - "0.0.0.0"
      - --JsonRpc.Port
      - "${HTTP_PORT}"
      - --JsonRpc.WebSocketsPort
      - "${WS_PORT}"
      - --JsonRpc.EngineHost
      - "0.0.0.0"
      - --JsonRpc.EnginePort
      - "${AUTH_PORT}"
      - --JsonRpc.JwtSecretFile=/secrets/jwtsecret
      - --Sync.FastSync
      - "true"
      - --config
      - xdai
      - --Pruning.Enabled
      - "true"
      - --Pruning.CacheMb
      - "4096"
      - --TxPool.Size
      - "4096"
      - --Sync.AncientBodiesBarrier
      - "1"
      - --Sync.AncientReceiptsBarrier
      - "1"
      - --Pruning.FullPruningThresholdMb
      - "180000"
    volumes:
      - ./nethermind-data:/var/lib/nethermind

  lighthouse-xdai:
    image: sigp/lighthouse:latest-modern
    hostname: node
    restart: unless-stopped
    command: |
      lighthouse beacon_node
      --network gnosis
      --checkpoint-sync-url ${CHECKPOINT_RPC_URL}
      --discovery-port ${CL_P2P_PORT}
      --port ${CL_P2P_PORT}
      --eth1-endpoints ${RPC_URL}
      --datadir /home/.eth2/beaconchaindata
      --http
      --http-address 0.0.0.0
      --http-port ${CL_HTTP_PORT}
      --enr-address ${PUBLIC_IP}
      --enr-udp-port ${CL_P2P_PORT}
      --target-peers 80
      --metrics 
      --metrics-address 0.0.0.0
      --metrics-allow-origin *
      --debug-level info
      --execution-endpoint ${EXECUTION_ENDPOINT}
      --execution-jwt "/secrets/jwtsecret"
    ports:
      - '${CL_P2P_PORT}:${CL_P2P_PORT}/tcp'
      - '${CL_P2P_PORT}:${CL_P2P_PORT}/udp'
      # - '${CL_HTTP_PORT}:${CL_HTTP_PORT}'
    volumes:
      - ./beaconchaindata:/home/.eth2/beaconchaindata
      - ./secrets:/secrets